Setup Telemetry Manager Repository
kyma-project/telemetry-manager pull request #1
Opened 2023-02-07 12:46 UTC by hisarbalik

**Description**

Changes proposed in this pull request:

- Code owner list updated
- Dummy code and dummy tests added
- Readme, license, contribution and code of conducts added

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/16745

2023-02-07 14:06 UTC, hisarbalik commented
/retest

2023-02-07 14:42 UTC, hisarbalik commented
/retest

2023-02-07 14:47 UTC, hisarbalik commented
/test pre-telemetry-manager-operator-lint

2023-02-08 10:43 UTC, hisarbalik commented
/retest

2023-02-08 10:43 UTC, hisarbalik commented
/test pull-telemetry-manager-lint

2023-02-08 10:44 UTC, hisarbalik commented
/test hisarbalik_test_of_prowjob_pull-telemetry-manager-lint

2023-02-10 16:31 UTC, chrkl commented on common/makefiles/generic-make-go.mk
> +# Default configuration
Let's get rid of this immediately. As far as I could see in test-infra, we only use the `lint` and `test-local` targets from our own Makefile. Let's revert this to something close to a "normal" Kubebuilder project Makefile.

2023-02-13 08:34 UTC, skhalash requested changes

2023-02-13 08:34 UTC, skhalash commented on Makefile
> +
Would be nice if we could get rid of the local suffixes

2023-02-13 11:10 UTC, skhalash approved these changes

2023-02-13 11:11 UTC, merged