fix: Panic on missing TLS configuration
kyma-project/telemetry-manager pull request #1215
Opened 2024-06-26 11:43 UTC by TeodorSAP

## Description

Changes proposed in this pull request (what was done and why):

- Add extra-checks for scenarios when either key or cert (or both) are missing from the TLS configuration
- Add 2 extra ReasonTLSConfigurationInvalid messages:
   - `ErrMissingAll`: "no TLS configuration provided, missing certificate, private key, and CA""
   - `ErrMissingCertKey`: "missing certificate or/and private key, and CA was not provided"
- Add extra UTs to test the implemented scenarios

Changes refer to particular issues, PRs or documents:

- Resolve #1205 

## Traceability
- [ ] The PR is linked to a GitHub issue.
- [ ] The PR has a milestone set.
- [ ] The PR has a respective `area` and `kind` label.
- [ ] The follow-up issues (if any) are linked in the `Related Issues` section.
- [ ] If the change is user-facing, the documentation has been adjusted.
- [ ] The feature is unit-tested.
- [ ] The feature is e2e-tested.

2024-07-01 09:05 UTC, skhalash requested changes

2024-07-01 09:05 UTC, skhalash commented on internal/tlscert/tls_cert_validator.go
> +}
Is it necessary? Does it have to be exported?

2024-07-01 09:05 UTC, skhalash commented on internal/tlscert/tls_cert_validator.go
> -				return err
I understand the intention of moving all parsing in a separate function, but IMHO it looks more confusing than before:
1. The function is called parse. It takes a key, a cert, and a CA cert and returns 2 certs. I know that we are not interested in the parsed key, but it still looks illogical.
2. It returns 2 certs and it's not obvious from the signature which is the normal cert and which is the CA cert. You could solve it using named return values, but it's also not very common in our codebase.

IMHO, keeping it the way it was is easier to read.

2024-07-01 10:55 UTC, TeodorSAP commented on internal/conditions/tls_cert_conditions.go
> +	// No Error
I just thought it was cleaner, but I will remove them

2024-07-01 10:59 UTC, TeodorSAP commented on test/e2e/logs_mtls_missing_values_test.go
> +		})
I just wanted to check that it is healthy in this particular scenarios, i.e. when missing certain TLS configuration parameters. If you think that's unnecessary, I can remove it, but I thought one extra-check won't harm, especially in these edge-cases

2024-07-01 11:36 UTC, skhalash requested changes

2024-07-01 11:36 UTC, skhalash commented on internal/testutils/pipeline_opts.go
As discussed, let us remove them and extend [OTLP|HTTP]ClientTLS to take the whole TLS struct as an argument

2024-07-01 13:39 UTC, TeodorSAP commented on internal/testutils/pipeline_opts.go
I've done something in-between: Just replaced my option methods with a `[OTLP][HTTP]ClientCustomTLS` function. I think the simple `[OTLP][HTTP]ClientTLS` function still has its value since removing it will generate some unnecessary boilerplate-code for the other e2e tests.

2024-07-01 13:40 UTC, TeodorSAP commented on internal/testutils/pipeline_opts.go
Let me know if you agree with my solution

2024-07-01 13:50 UTC, skhalash commented on internal/testutils/pipeline_opts.go
I agree that old helpers are a bit more lightweight, but I am not fond of `CustomTLS` (there is nothing custom there). Maybe let's keep both options, but rename them:
`OTLPClientTLS` -> `OTLPClientTLSFromStrings`
`OTLPClientCustomTLS` -> `OTLPClientTLS`

2024-07-02 09:38 UTC, skhalash approved these changes

2024-07-02 11:35 UTC, a-thaler commented
/cla

2024-07-02 11:35 UTC, merged