feat: Allow disabling pod and/or container metrics
kyma-project/telemetry-manager pull request #1241
Opened 2024-07-02 15:18 UTC by shorim

## Description

Changes proposed in this pull request (what was done and why):

- 

Changes refer to particular issues, PRs or documents:

- 

## Traceability
- [ ] The PR is linked to a GitHub issue.
- [ ] The PR has a milestone set.
- [ ] The PR has a respective `area` and `kind` label.
- [ ] The follow-up issues (if any) are linked in the `Related Issues` section.
- [ ] If the change is user-facing, the documentation has been adjusted.
- [ ] The feature is unit-tested.
- [ ] The feature is e2e-tested.

2024-07-05 13:10 UTC, skhalash requested changes

2024-07-08 00:55 UTC, shorim commented on apis/telemetry/v1beta1/metricpipeline_types.go
> +	// Describes the Kubernetes resources for which runtime metrics are scraped.
after discussion, we agreed that scraping is also suitable here and preferred also to use it to keep the terminology consistent

2024-07-08 00:58 UTC, shorim commented on internal/otelcollector/config/metric/gateway/config_builder.go
> +		processors = append(processors, namespaceFilterID(pipeline.Name, metric.InputSourceOtlp))
The otehr ID maker func check whether or not the filter should be added, while the `namespaceFilterID ` just formats the filter ID with a specific pattern. I renamed it to `formatNamespaceFilterID` to make the difference more visible.

2024-07-08 05:28 UTC, IwonaLanger commented on docs/user/04-metrics.md
> +The agent configures the [kubletstatsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kubeletstatsreceiver) for the metric groups `pod` and `container`.
```suggestion
The agent configures the [kubletstatsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kubeletstatsreceiver) for the metric groups `pod` and `container`. With that, [system metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/documentation.md) related to containers and Pods get collected by default.
```

2024-07-08 05:28 UTC, IwonaLanger commented on docs/user/04-metrics.md
> +It is possible to selectively disable the collection of the pod or container metrics by defining the `resources` section in the `runtime` input.
```suggestion
It is possible to selectively disable the collection of the Pod or container metrics by defining the `resources` section in the `runtime` input.
```

2024-07-08 05:28 UTC, IwonaLanger commented on docs/user/04-metrics.md
> +The following example drops the runtime pod metrics and only collects runtime container metrics:
```suggestion
The following example drops the runtime Pod metrics and only collects runtime container metrics:
```

2024-07-08 05:28 UTC, IwonaLanger commented on docs/user/04-metrics.md
> +The following example drops the runtime container metrics and only collects runtime pod metrics:
```suggestion
The following example drops the runtime container metrics and only collects runtime Pod metrics:
```

2024-07-08 05:28 UTC, IwonaLanger commented on docs/user/resources/05-metricpipeline.md
> +| **input.&#x200b;runtime.&#x200b;namespaces**  | object | Describes whether runtime metrics from specific Namespaces are selected. System Namespaces are disabled by default. |
```suggestion
| **input.&#x200b;runtime.&#x200b;namespaces**  | object | Describes whether runtime metrics from specific namespaces are selected. System namespaces are disabled by default. |
```

2024-07-08 05:28 UTC, IwonaLanger commented on docs/user/resources/05-metricpipeline.md
> +| **input.&#x200b;runtime.&#x200b;resources.&#x200b;pod**  | object | Configures pod runtime metrics scraping. By default, pod runtime metrics are scraped when runtime input is enabled. |
```suggestion
| **input.&#x200b;runtime.&#x200b;resources.&#x200b;pod**  | object | Configures Pod runtime metrics scraping. By default, Pod runtime metrics are scraped when runtime input is enabled. |
```

2024-07-08 09:14 UTC, NHingerl commented on docs/user/04-metrics.md
> +The agent configures the [kubletstatsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kubeletstatsreceiver) for the metric groups `pod` and `container`.
```suggestion
The agent configures the [kubletstatsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kubeletstatsreceiver) for the metric groups `pod` and `container`. With that, [system metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/documentation.md) related to containers and Pods are collected by default.
```

2024-07-08 15:40 UTC, NHingerl commented on docs/user/04-metrics.md
> +The agent configures the [kubletstatsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kubeletstatsreceiver) for the metric groups `pod` and `container`.
```suggestion
The agent configures the [kubletstatsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kubeletstatsreceiver) for the metric groups `pod` and `container`. With that, [system metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/documentation.md) related to containers and Pods are collected by default.
```

2024-07-08 15:40 UTC, NHingerl commented on docs/user/04-metrics.md
> +It is possible to selectively disable the collection of the Pod or container metrics by defining the `resources` section in the `runtime` input.
```suggestion
If you want to disable the collection of the Pod or container metrics, define the `resources` section in the `runtime` input.
```

2024-07-08 16:40 UTC, NHingerl approved these changes

2024-07-08 18:48 UTC, skhalash approved these changes

2024-07-08 18:58 UTC, merged