fix: Fix flaky e2e tests
kyma-project/telemetry-manager pull request #1266
Opened 2024-07-10 14:00 UTC by k15r

## Description

Changes proposed in this pull request (what was done and why):

- 

Changes refer to particular issues, PRs or documents:

- 

## Traceability
- [ ] The PR is linked to a GitHub issue.
- [ ] The PR has a milestone set.
- [ ] The follow-up issues (if any) are linked in the `Related Issues` section.
- [ ] If the change is user-facing, the documentation has been adjusted.
- [ ] The feature is unit-tested.
- [ ] The feature is e2e-tested.

2024-07-16 12:13 UTC, TeodorSAP requested changes

2024-07-16 12:14 UTC, TeodorSAP commented on test/e2e/logs_resources_test.go
> +			}, periodic.EventuallyTimeout, periodic.DefaultInterval).Should(BeTrue(), "ClusterRole should be deleted")
I'm still not sure which of the two options is better, but certainly we should use the same one everywhere.

2024-07-16 12:28 UTC, k15r commented on test/e2e/logs_resources_test.go
> +			}, periodic.EventuallyTimeout, periodic.DefaultInterval).Should(BeTrue(), "ServiceAccount should be deleted")
eventually allows you to specify a reason message for a failure as an additional argument.

2024-07-16 12:48 UTC, k15r commented on test/integration/istio/metrics_self_monitor_outage_test.go
> +			}, "1m", "10s").Should(Succeed())
this eventually block is only necessary to work around "resource has been modified" issues with kubernetes. There should not be any need to modify it.

2024-07-17 08:22 UTC, TeodorSAP approved these changes

2024-07-17 08:36 UTC, merged