chore: Print test cases as part of test execution
kyma-project/telemetry-manager pull request #1365
Opened 2024-08-20 11:08 UTC by a-thaler

## Description

Changes proposed in this pull request (what was done and why):

- Add debug option to ginkgo commands to list executed test cases for documentation purpose

Changes refer to particular issues, PRs or documents:

- 

## Traceability
- [ ] The PR is linked to a GitHub issue.
- [ ] The follow-up issues (if any) are linked in the `Related Issues` section.
- [ ] If the change is user-facing, the documentation has been adjusted.
- [ ] The feature is unit-tested.
- [ ] The feature is e2e-tested.

2024-08-21 12:39 UTC, TeodorSAP requested changes

2024-08-21 12:39 UTC, TeodorSAP commented on hack/gardener-integration-test.sh
> +    ${GINKGO} run --junit-report=junit-report --tags istio --label-filter="integration" test/integration/istio
Isn't the `.xml` extension missing here? I saw you are using it everywhere else, and it looks a bit inconsistent.

2024-08-22 08:11 UTC, a-thaler commented on hack/gardener-integration-test.sh
> +    ${GINKGO} run --junit-report=junit-report --tags istio --label-filter="integration" test/integration/istio
```suggestion
    ${GINKGO} run --junit-report=junit-report.xml --tags istio --label-filter="integration" test/integration/istio
```

2024-08-22 11:41 UTC, TeodorSAP approved these changes

2024-08-22 16:34 UTC, merged