Improve fluent bit config reconciliation
kyma-project/telemetry-manager pull request #202
Opened 2023-06-06 14:31 UTC by chrkl

**Description**

Changes proposed in this pull request:

- Include static Fluent Bit configuration into checksum calculation
- Add owner references to all created resources
- Remove unnecessary checks for changed resources
- Add missing watch to LogParser controller

**Related issue(s)**

2023-06-06 15:15 UTC, chrkl commented
/retest

2023-06-06 15:22 UTC, chrkl commented
/retest

2023-06-07 09:07 UTC, skhalash requested changes
Looks good 👍🏻  One question what is with the finalizers? We don't need to add them anymore, but we should cleanup if they are set?

2023-06-07 09:07 UTC, skhalash commented on internal/reconciler/logparser/sync_test.go
> +	require.Len(t, cm.OwnerReferences, 1)
Let's maybe test who is the owner?

2023-06-07 10:04 UTC, chrkl commented
> Looks good 👍🏻 One question what is with the finalizers? We don't need to add them anymore, but we should cleanup if they are set?

We cannot get rid of the finalizer yet since it is still required to clean up the pipeline specific ConfigMap keys on deletion. Adding the OwnerReferences has the purpose to reconcile the pipeline if the ConfigMap is touched by the user and also ensures that no empty ConfigMap is left after all pipelines are deleted.

2023-06-07 10:14 UTC, chrkl commented
/retest

2023-06-07 10:29 UTC, chrkl commented
/retest

2023-06-07 10:51 UTC, skhalash approved these changes

2023-06-07 10:51 UTC, merged