Introduce make targets to run e2e tests per signal
kyma-project/telemetry-manager pull request #266
Opened 2023-07-17 12:10 UTC by chrkl

**Description**

Adding more test-cases to the e2e-test suite make the test runs to take more time and also increased flakiness. This PR adds make targets to run the tests for a specific signal with the goal to improve the development workflow and have separate pipelines in future.

Changes proposed in this pull request:

- Introduce make targets to run e2e tests per signal

**Related issue(s)**

2023-07-17 12:27 UTC, skhalash requested changes

2023-07-17 12:27 UTC, skhalash commented on config/manager/kustomization.yaml
> +  newTag: latest
Please, revert this change

2023-07-17 12:29 UTC, chrkl commented on config/manager/kustomization.yaml
> +  newTag: latest
Done

2023-07-18 09:09 UTC, chrkl commented
/retest

2023-07-18 12:16 UTC, skhalash approved these changes

2023-07-18 12:44 UTC, chrkl commented
/retest

2023-07-18 13:16 UTC, merged