Test istio access logs
kyma-project/telemetry-manager pull request #315
Opened 2023-08-03 15:36 UTC by rakesh-garimella

## Description

Changes proposed in this pull request:

- ...

## Related Issues and Documents

Closes:

Related issues:

## Traceability

- [ ] The PR is linked to a GitHub Issue.
- [ ] New features have a milestone label set.
- [ ] New features have defined acceptance criteria in a corresponding GitHub Issue, and all criteria are satisfied with this PR.
- [ ] The corresponding GitHub Issue has a respective `area` label.
- [ ] The follow-up issues (if any) are linked in the `Related Issues` section.

## Testability

The feature is unit-tested:

- [ ] Yes.
- [ ] No, because unit tests are not needed.
- [ ] No, because of ...

The feature is e2e-tested:

- [ ] Yes.
- [ ] No, because e2e-tests are not needed.
- [ ] No, because of ...

Tests conducted for the PR:

## Codebase

- [ ] My code follows the [Effective Go](https://go.dev/doc/effective_go) style guidelines.
- [ ] The code was planned and designed following the defined architecture and the separation of concerns.
- [ ] The code has sufficient comments, particularly for all hard-to-understand areas.
- [ ] This PR adds value and shows no feature creep.
- [ ] I have augmented the test suite that proves my fix is effective or that my feature works.
- [ ] Adjusted the documentation if the change is user-facing.

2023-08-07 06:57 UTC, skhalash commented
/retest

2023-08-07 09:18 UTC, ameteiko requested changes

2023-08-07 09:18 UTC, ameteiko commented on test/testkit/kyma/istio/istio.go
> +package istio
`//go:build e2e` is missing

2023-08-07 09:18 UTC, ameteiko commented on test/integration/istio_access_logs_test.go
> +func makeIstioAccessLogsK8sObjects(mockNs, mockDeploymentName, sampleAppNs string) ([]client.Object, *mocks.URLProvider, string) {
Can we reuse the `makeLogsTestK8sObjects` or some of the parts of it?

2023-08-07 09:18 UTC, ameteiko commented on test/integration/suite_test.go
> +var _ = BeforeSuite(func() {
Can we share this code with the E2E Acceptance tests (the main e2e test suite)?

2023-08-07 09:18 UTC, ameteiko commented on test/testkit/mocks/urlprovider.go
> +	metricPod string
metricPod -> metricPodURL

2023-08-07 09:23 UTC, rakesh-garimella commented
related prow job run: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_telemetry-manager/315/rakesh-garimella_test_of_prowjob_pull-telemetry-manager-integra/1688471194837192704

Prow Job PR: https://github.com/kyma-project/test-infra/pull/8561

2023-08-07 11:04 UTC, skhalash commented
/retest

2023-08-07 11:21 UTC, skhalash commented
/retest

2023-08-07 14:51 UTC, rakesh-garimella commented
/retest

2023-08-08 08:09 UTC, rakesh-garimella commented
/retest

2023-08-08 08:17 UTC, ameteiko approved these changes

2023-08-08 08:19 UTC, merged